[build]
builder = "NIXPACKS"
buildCommand = "cd apps/backend && npm install && npm run build && npm prune --production"

[deploy]
startCommand = "cd apps/backend && npm run start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
