[build]
builder = "NIXPACKS"
buildCommand = "cd apps/backend && npm install --include=dev && npm run build && ls .medusa/server/public/admin/assets | head -3 && npm prune --omit=dev"

[deploy]
startCommand = "cd apps/backend && npm run start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
