services:
  - type: web
    name: maoshu-backend
    env: node
    region: singapore
    plan: starter
    rootDir: apps/backend
    buildCommand: npm install --include-workspace-root --workspace=apps/backend && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        sync: false
      - key: ADMIN_CORS
        sync: false
      - key: AUTH_CORS
        sync: false
      - key: S3_FILE_URL
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ENDPOINT
        sync: false
